const ACTION_TYPES = {
 'SIGN_IN': 'SIGN_IN',
 'SIGN_IN_SUCCESS': 'SIGN_IN_SUCCESS',
 'SIGN_IN_ERROR': 'SIGN_IN_ERROR',
 'GET_LIST_USER': 'GET_LIST_USER',
 'GET_LIST_USER_SUCCESS': 'GET_LIST_USER_SUCCESS',
 'GET_LIST_USER_ERROR': 'GET_LIST_USER_ERROR',
 'GET_USER_DETAIL': 'GET_USER_DETAIL',
 'GET_USER_DETAIL_SUCCESS': 'GET_USER_DETAIL_SUCCESS',
 'GET_USER_DETAIL_ERROR': 'GET_USER_DETAIL_ERROR',
 'DELETE_USER': 'DELETE_USER',
 'DELETE_USER_SUCCESS': 'DELETE_USER_SUCCESS',
 'DELETE_USER_ERROR': 'DELETE_USER_ERROR'
};

export default ACTION_TYPES;
